#!/usr/bin/env node
/**
 * Mint the secrets a Supabase stack needs, and print them as .env lines.
 *
 *   node scripts/mint-keys.mjs              # print to stdout
 *   node scripts/mint-keys.mjs >> supabase/.env
 *
 * The anon and service_role "keys" are just long-lived HS256 JWTs signed with
 * JWT_SECRET, carrying a `role` claim. PostgREST reads that claim and does
 * SET ROLE, which is what makes row-level security apply — so these are not
 * opaque API keys, they are credentials that decide which Postgres role a
 * request runs as.
 *
 * Consequences worth knowing:
 *   • Changing JWT_SECRET invalidates BOTH keys and signs every user out.
 *   • SERVICE_ROLE_KEY bypasses RLS entirely. It belongs on a server, never in
 *     NEXT_PUBLIC_* and never in a browser.
 *   • ANON_KEY is public by design — it ships to every visitor. It grants only
 *     what the `anon` role's policies allow.
 *
 * Run once per environment. Local dev and production must not share a secret.
 */
import { randomBytes, createHmac } from "node:crypto";

const YEARS = 10;

const b64url = (buf) =>
  Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

function jwt(payload, secret) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const body = b64url(JSON.stringify(payload));
  const signature = b64url(createHmac("sha256", secret).update(`${header}.${body}`).digest());
  return `${header}.${body}.${signature}`;
}

const secret = randomBytes(32).toString("hex"); // 64 chars; GoTrue wants >= 32
const iat = Math.floor(Date.now() / 1000);
const exp = iat + YEARS * 365 * 24 * 60 * 60;

const anon = jwt({ role: "anon", iss: "supabase", iat, exp }, secret);
const service = jwt({ role: "service_role", iss: "supabase", iat, exp }, secret);

process.stdout.write(
  [
    `# Generated by scripts/mint-keys.mjs on ${new Date().toISOString()}`,
    `# Keys expire ${new Date(exp * 1000).toISOString().slice(0, 10)}.`,
    ``,
    `POSTGRES_PASSWORD=${randomBytes(24).toString("hex")}`,
    `JWT_SECRET=${secret}`,
    `ANON_KEY=${anon}`,
    `SERVICE_ROLE_KEY=${service}`,
    `SECRET_KEY_BASE=${randomBytes(32).toString("hex")}`,
    // EXACTLY 16 characters. Realtime encrypts its tenant secrets with
    // aes_128_ecb, which takes a 16-BYTE key, and it passes this string
    // straight through as the key material. Anything else and the container
    // crash-loops on boot with `:badarg ... Bad key size` from deep inside
    // Erlang's crypto, seeding a tenant it never finishes creating.
    `REALTIME_DB_ENC_KEY=${randomBytes(8).toString("hex")}`,
    ``,
  ].join("\n")
);
